feat(breadcrumb/basic): restyling
SUI-Components/SUIComponents pull request #101
Opened 2017-06-26 12:55 UTC by JoanClaret

feat(breadcrumb/basic): restyling

2017-06-26 13:44 UTC, naxhh requested changes
NIce work!

But you should add a BREAKING CHANGE in there.. because component props have changed

2017-06-26 13:45 UTC, JoanClaret commented
yes, but at this moment, nobody is using this component. that's why i did not do it.

2017-06-26 14:01 UTC, JoanClaret commented
added sass variables in order to be able to customize from theme

2017-06-27 07:02 UTC, naxhh approved these changes

2017-06-27 08:46 UTC, miduga commented on components/breadcrumb/basic/src/index.js
> +    this._breadcrumb.classList.add('is-expanded')
Why not using state for that?

2017-06-27 08:47 UTC, miduga commented on components/breadcrumb/basic/src/index.js
> +    this._breadcrumb = null
You just could do:

```
_breadcrumb = null
```

And you remove the constructor.

2017-06-28 06:47 UTC, JoanClaret commented on components/breadcrumb/basic/src/index.js
> +    this._breadcrumb.classList.add('is-expanded')
i thought that using refs would be better option, but i might be wrong.
fixed!

2017-06-28 06:48 UTC, JoanClaret commented on components/breadcrumb/basic/src/index.js
> +    this._breadcrumb = null
actually, since we are now using state, we don't need to initialize this value.

2017-06-28 07:13 UTC, midudev approved these changes

2017-06-28 07:14 UTC, merged