feat(atom/card): using $bgc-atom-card-hover to keep styles backwards …
SUI-Components/SUIComponents pull request #1063
Opened 2020-03-31 15:32 UTC by PablitoGS

…compatible

2020-03-31 16:46 UTC, andresin87 approved these changes

2020-03-31 16:47 UTC, andresin87 requested changes
I think you dont need the final "default" written value

2020-04-01 07:45 UTC, nucliweb approved these changes

2020-04-01 07:45 UTC, beatrizip approved these changes

2020-04-01 07:52 UTC, merged