Feature/breadcrumb adjust
SUI-Components/SUIComponents pull request #108
Opened 2017-07-03 12:12 UTC by JoanClaret

fix button color
adding `background color` and `box shadow` properties in order to fit with motor design requeriments

don't really know why tab-basic and tab-content is upgrading a new version.

2017-07-03 12:18 UTC, naxhh commented on components/breadcrumb/basic/package.json
> +  "version": "1.4.0",
All package versions should be changed when release and not by hand, right?

2017-07-03 12:18 UTC, naxhh requested changes
Remove package version changes

2017-07-03 13:00 UTC, JoanClaret commented
@naxhh fixed!

2017-07-04 07:14 UTC, naxhh approved these changes

2017-07-04 07:37 UTC, merged