feat(molecule/select): add disabled border to select
SUI-Components/SUIComponents pull request #1150
Opened 2020-06-05 12:32 UTC by davidmartin84

**BEFORE:**

<img width="663" alt="Captura de pantalla 2020-06-05 a las 14 25 03" src="https://user-images.githubusercontent.com/6562273/83876542-52a8f380-a739-11ea-9893-94fffe7217cd.png">

**AFTER:**

<img width="674" alt="Captura de pantalla 2020-06-05 a las 14 31 29" src="https://user-images.githubusercontent.com/6562273/83876560-56d51100-a739-11ea-861c-e6bba6eebb48.png">

2020-06-05 13:13 UTC, quinwacca approved these changes

2020-06-05 14:30 UTC, nucliweb approved these changes

2020-06-08 06:08 UTC, jordevo approved these changes

2020-06-08 06:22 UTC, AgonisticKatai approved these changes

2020-06-08 06:27 UTC, devictoribero approved these changes

2020-06-08 06:35 UTC, andresin87 requested changes
I think it's better if you define:
```
$bd-molecule-select-disabled = $bd-atom-input-disabled;
```

and use it in line 44:
```
border: $bd-molecule-select-disabled;
```
in order to be customized by component like $c-select-list-arrow-disabled

2020-06-08 07:30 UTC, andresin87 requested changes

2020-06-08 07:30 UTC, andresin87 commented on components/molecule/select/src/index.scss
>            background: $bgc-atom-input-disabled;
same thing as `$bd-molecule-select-disabled` is for `$bgc-atom-input-disabled`. plzz

2020-06-08 07:53 UTC, andresin87 approved these changes

2020-06-08 07:58 UTC, merged