feat(components/atom/badge): add secundary type
SUI-Components/SUIComponents pull request #1692
Opened 2021-09-20 10:31 UTC by adriadoz

## ATOM/BADGE

### Types of changes

-  New feature (non-breaking change which adds functionality)

### Description, Motivation and Context
- Add secondary by default
- Move demo from playground

### Screenshots - Animations
![image](https://user-images.githubusercontent.com/13208031/133988490-696b1add-612c-42d8-a513-c92adabbe3db.png)

2021-09-20 10:37 UTC, oriolpuig approved these changes

2021-09-20 10:44 UTC, nachoAdevinta approved these changes

2021-09-20 10:51 UTC, andresin87 commented
plz wait

2021-09-20 11:04 UTC, andresin87 commented on components/atom/badge/demo/index.js
> +              type={atomBadgeTypes.SECUNDARY}
SEC`O`NDARY

2021-09-20 11:05 UTC, andresin87 requested changes

2021-09-20 11:05 UTC, andresin87 commented on components/atom/badge/demo/index.js
> +} = window.DOC
import from '@s-ui/documantation-library'

2021-09-20 11:20 UTC, andresin87 commented
Secondary token is only used by RE different than accent color. Let's find some other different approach.

2021-09-22 07:28 UTC, andresin87 commented
- [x] Playground removed
- [x] Demo made in js.
- [x] Demo articles splitted
- [x] Component constants moved to a separatd file.
- [x] Component Code in its own reserved file.
- [x] Package index.js file reserved for indexing package resorces only.
- [x] Component classnames refactored.
- [ ] isFitted.
- [x] Custom-types demo article added.

2021-09-22 07:56 UTC, andresin87 approved these changes

2021-09-22 08:53 UTC, merged