feat(components/atom/panel): switch to PolymorphicElement
SUI-Components/SUIComponents pull request #2059
Opened 2022-03-11 12:17 UTC by tonyghiani

## atom/panel

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Only
- [ ] Refactor

### Description, Motivation and Context
In order to be able to semantically render the panel component with different HTML tags, the base element of the panel need to be replaced with the PolymorphicElement.

2022-03-11 12:20 UTC, slaverise approved these changes

2022-03-11 12:22 UTC, javiauso approved these changes

2022-03-11 12:52 UTC, andresin87 commented on components/atom/panel/src/ColorPanel.js
> +  ...PolymorphicElement.propTypes,
do not because react-docgen does not make the docu with this meth

2022-03-11 12:53 UTC, andresin87 commented on components/atom/panel/src/ImagePanel.js
> +  ...PolymorphicElement.propTypes,
same

2022-03-11 12:53 UTC, andresin87 requested changes
some changes

2022-03-11 13:01 UTC, andresin87 approved these changes

2022-03-14 08:06 UTC, andresin87 approved these changes
Looks like ImagePanel and ColorPanel are AtomPanel resulting component, and this is not providing the 'as' prop method documented to them. Add the 'as' prop to the AtomPanel and document it also 🙏.

2022-03-14 08:07 UTC, andresin87 requested changes
Looks like ImagePanel and ColorPanel are AtomPanel resulting component, and this is not providing the 'as' prop method documented to them. Add the 'as' prop to the AtomPanel and document it also 🙏.

2022-03-14 08:13 UTC, tonyghiani commented
> Looks like ImagePanel and ColorPanel are AtomPanel resulting component, and this is not providing the 'as' prop method documented to them. Add the 'as' prop to the AtomPanel and document it also 🙏.

I'll definitely add this to the documentation! About passing this prop inside the AtomPanel, properties are already spread and the `as` property will be passed to the other two, would you prefer to explicitly restructure the as property and set it in both possible scenarios in the index.js file?

2022-03-14 08:34 UTC, andresin87 commented
> > Looks like ImagePanel and ColorPanel are AtomPanel resulting component, and this is not providing the 'as' prop method documented to them. Add the 'as' prop to the AtomPanel and document it also 🙏.
> 
> @andresin87 I'll definitely add this to the documentation! About passing this prop inside the AtomPanel, properties are already spread and the `as` property will be passed to the other two, would you prefer to explicitly restructure the as property and set it in both possible scenarios in the index.js file?

declare it in the propTypes if you consider it must be documented.

2022-03-14 09:41 UTC, andresin87 approved these changes

2022-03-14 09:47 UTC, merged