Feature/molecule photo uploader content
SUI-Components/SUIComponents pull request #2105
Opened 2022-04-08 10:31 UTC by AitorRodriguez990

## Category/Component

#### `❓ Ask`

**TASK**:  [#2049](https://github.com/SUI-Components/sui-components/discussions/2049)

### Types of changes

- [ ] 🪲 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🧾 Documentation
- [x] 📷 Demo
- [ ] 🧪 Test
- [ ] 🧠 Refactor
- [ ] 💄 Styles

### Description, Motivation and Context

On the Real Estate vertical we need to add labels on photos, so I iterate the `MoleculePhotoUploader` component to be able to insert content inside.

### Screenshots - Animations

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/13108014/162418560-331639b0-a6a3-4f1b-a48e-a3dfb91be91f.png">

2022-04-08 10:38 UTC, midudev approved these changes

2022-04-08 10:41 UTC, andresin87 commented on components/molecule/photoUploader/src/styles/settings.scss
> +$p-photo-uploader-content: $p-m !default;
not necessary, we must offer an empty canvas and delegate the spacing margins-paddings L&F to the consumer of the space

2022-04-08 10:41 UTC, andresin87 commented on components/molecule/photoUploader/src/styles/index.scss
> +      padding: $p-photo-uploader-content;
not necessary

2022-04-08 10:52 UTC, andresin87 requested changes
👏👏👏

2022-04-08 10:52 UTC, andresin87 commented on components/molecule/photoUploader/src/ThumbCard/index.js
> +      <div className={CONTENT_THUMB_CARD_CLASS_NAME}>{content()}</div>
```suggestion
      {content !== undefined && <div className={CONTENT_THUMB_CARD_CLASS_NAME}>{content()}</div>}
```

2022-04-08 10:52 UTC, andresin87 commented on components/molecule/photoUploader/src/PhotosPreview/index.js
> +            content={() => content(file, index)}
```suggestion
            content={() => content({file, index})}
```

2022-04-08 10:52 UTC, andresin87 commented on components/molecule/photoUploader/demo/articles/InitialPhotosArticle.js
> +const _content = (image, index) => {
```suggestion
const _content = ({file: image, index}) => {
```

2022-04-08 10:52 UTC, andresin87 commented on components/molecule/photoUploader/src/PhotosPreview/index.js
> +            content={() => content(file, index)}
creo que tb funcionaria
`content={content.bind(undefined, {file, index})}`

2022-04-08 10:53 UTC, andresin87 commented on components/molecule/photoUploader/src/styles/index.scss
> +      padding: $p-photo-uploader-content;
I think this might be in demos styles and verticals

2022-04-08 10:55 UTC, andresin87 commented
The deployed demo is not storing the changes through the image selectors... Is it right?

2022-04-08 10:58 UTC, andresin87 commented
Better add a new demo for documenting the content prop copy-pasting the initialProtos one, not reusing it and also document the prop usage in that new article

2022-04-09 22:03 UTC, AitorRodriguez990 commented
Thank you @andresin87 👌 

I applied your feedback, can you review it, please? 

Now, I only have a problem: I can't change the array values, like the `label`, because the component is a controlled component and has its own state. Can you help me here, please?

2022-04-11 07:31 UTC, andresin87 commented on components/molecule/photoUploader/src/index.js
> +  content: PropTypes.func,
I've been thinking about that. Maybe content is too much ambiguous. Think about `fileChildren` or `childenFile` or something similar

2022-04-11 07:35 UTC, andresin87 commented
With Content - Select example might work keeping the user selected value

2022-04-12 15:16 UTC, andresin87 approved these changes

2022-04-13 07:36 UTC, merged