feat(components/molecule/photoUploader): add overflow hidden to make visible the defined border-radius
SUI-Components/SUIComponents pull request #2134
Opened 2022-05-03 17:09 UTC by quinwacca

## molecule/PhotoUploader
#### `🔍 Show`

**TASK**: [MTR-53299](https://jira.scmspain.com/browse/MTR-53299)

### Types of changes

- [x] 💄 Styles

### Description, Motivation and Context
Add overflow hidden to make visible the defined border-radius

### Screenshots - Animations
BEFORE:
![Captura de Pantalla 2022-05-03 a las 19 05 19](https://user-images.githubusercontent.com/37936498/166503956-81cacd0a-c98a-4d47-b988-84d94b77cc6d.png)

NOW (with dramatic border-radius applied):
![Captura de Pantalla 2022-05-03 a las 19 05 28](https://user-images.githubusercontent.com/37936498/166504003-2a5d3c0d-1451-4ff4-b98a-11147584a2d4.png)

2022-05-03 17:25 UTC, jordevo approved these changes

2022-05-03 17:31 UTC, turolopezsanabria requested changes
🔴  This change trims the options in the option "with Content, example Select" 

https://user-images.githubusercontent.com/23620759/166507204-05f19a46-ce20-4cf9-8cfa-4e7f1b4eda1e.mov

2022-05-03 17:35 UTC, quinwacca commented
> 🔴 This change trims the options in the option "with Content, example Select"
> 
>  content.hidden.mov

Now I understand why this property had been removed when the children content is added 🤦‍♂️

2022-05-04 12:31 UTC, turolopezsanabria approved these changes
wow, nice workaround
thnx!

2022-05-04 12:37 UTC, merged