feat(components/atom/tag): add customizable padding
SUI-Components/SUIComponents pull request #2194
Opened 2022-06-02 12:09 UTC by nguasch

## Category/Component

`🔍 Show`

**TASK**: 

### Types of changes

- [ ] 🪲 Bug fix (non-breaking change which fixes an issue)
- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🧾 Documentation
- [ ] 📷 Demo
- [ ] 🧪 Test
- [ ] 🧠 Refactor
- [ ] 💄 Styles

### Description, Motivation and Context
Add customizable variable for padding only for medium tag and it has icon and close button.
It's a requirement form UI to adjust tags in that case

### Screenshots - Animations
medium tag with icon and close:
![Screenshot 2022-06-02 at 14 04 40](https://user-images.githubusercontent.com/74129/171625569-c351f58d-8966-4cbe-a116-20a386dbeb44.png)
large tag with icon and close: 
![Screenshot 2022-06-02 at 14 04 32](https://user-images.githubusercontent.com/74129/171625566-f73d86ef-913d-4407-b8e0-213036419b66.png)
medium tag with only icon:
![Screenshot 2022-06-02 at 14 04 52](https://user-images.githubusercontent.com/74129/171625574-1db6d52e-3f17-4a26-a823-055bd972bf72.png)

2022-06-02 14:57 UTC, andresin87 approved these changes

2022-06-02 14:57 UTC, andresin87 commented on components/atom/tag/src/_settings.scss
> +$p-atom-tag-medium-hasIcon-hasClose: $p-atom-tag-m !default;
hasClose is not only for medium and the padding might be also aded in small and large

```scss
$p-atom-tag-hasIcon-hasClose: (
  small: $p-atom-tag-s,
  medium: $p-atom-tag-m,
  large:  small: $p-atom-tag-l
) !default
```

2022-06-02 14:57 UTC, andresin87 commented on components/atom/tag/src/styles/index.scss
> +      padding: $p-atom-tag-medium-hasIcon-hasClose;
map.get($p-atom-tag-medium-hasIcon-hasClose, "medium")

and also with small and large

2022-06-02 14:58 UTC, andresin87 requested changes
.

2022-06-03 10:08 UTC, nguasch commented on components/atom/tag/src/styles/index.scss
> +      padding: $p-atom-tag-medium-hasIcon-hasClose;
Done!

2022-06-07 09:27 UTC, andresin87 approved these changes

2022-06-07 09:28 UTC, merged