refactor(components/molecule/avatar): Replace cloneElement with injector
SUI-Components/SUIComponents pull request #2346
Opened 2022-09-30 22:17 UTC by oegea

ISSUES CLOSED: #2329

## molecule/avatar

#### `❓ Ask`

**TASK**: #2329

### Types of changes

- [X] 🧠 Refactor

### Description, Motivation and Context

This PRs replaces `cloneElement`statements from  remaining places of the `molecule/avatar` component in favor of the sui `Injector` component.

Submitted for the hacktoberfest event. It should not have any visual effect, just a refactor.

Do not merge before https://github.com/SUI-Components/sui-components/pull/2345 to avoid missing dependency problems.

2022-10-02 08:04 UTC, andresin87 approved these changes

2022-10-02 21:19 UTC, andresin87 commented
take a look on #2348 
Its a cleaner result to remove the Children.toArray loop and directly wrap the children with the injector cuz it has that looping inside

2022-10-02 21:20 UTC, andresin87 requested changes
.

2022-10-03 07:31 UTC, oegea commented
@andresin87 

I suggest to close this PR as it is addressing the same issue than #2348 
IMHO, it makes no sense to adopt changes here if it has been solved on another PR.

2022-10-03 09:53 UTC, closed without merging