fix(components/atom/textarea): Fix issue with paddings in textarea
SUI-Components/SUIComponents pull request #2454
Opened 2022-11-02 15:24 UTC by slaverise

## atom/textarea
❓ Ask

### Types of changes

- [x] 🪲 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🧾 Documentation
- [ ] 📷 Demo
- [ ] 🧪 Test
- [ ] 🧠 Refactor
- [ ] 💄 Styles

### Description, Motivation and Context

There was an issue in the paddings for the text area, it was applying a different size for the box:
- padding-top: 8px vs padding-bottom: 2px
- padding-left: 8px vs padding-right: 2px

Also there was an issue on the height for maximum lines, for example in size=long the if the user typed 7 lines, the scrollbar was shown

### Screenshots - Animations

Padding issue:

![image](https://user-images.githubusercontent.com/3693800/199529860-fbdd13bd-5a1d-43d7-ad70-569f5f98cb05.png)

Fixed:

![image](https://user-images.githubusercontent.com/3693800/199529994-f332f044-309e-4865-9569-d02a86dd2dfe.png)

Scrollbar issue:

![image](https://user-images.githubusercontent.com/3693800/199530087-690665e1-f069-412c-b5d6-a7624ef06b7e.png)

Fixed:

![image](https://user-images.githubusercontent.com/3693800/199530120-a0e91246-9034-4aa8-aa9e-acd6e40b71e5.png)

2022-11-02 15:25 UTC, tonyghiani approved these changes

2022-11-02 15:53 UTC, turolopezsanabria approved these changes

2022-11-02 15:53 UTC, turolopezsanabria commented on components/atom/textarea/src/styles/settings.scss
>  $pl-atom-textarea: $p-l !default;
Do we still need this padding-left?

2022-11-02 17:33 UTC, slaverise commented on components/atom/textarea/src/styles/settings.scss
>  $pl-atom-textarea: $p-l !default;
True! I Will remove It!

2022-11-03 07:28 UTC, andresin87 requested changes
.

2022-11-07 09:34 UTC, andresin87 approved these changes

2022-11-07 10:50 UTC, merged