feat(components/molecule/collapsible): Custom toggle button and butto…
SUI-Components/SUIComponents pull request #2466
Opened 2022-11-16 11:43 UTC by hpintos

…n alignment

## Category/Component
🔍 Show

**TASK**: 

### Types of changes

- [x] ✨ New feature (non-breaking change which adds functionality)

### Description, Motivation and Context

We add two new features for this component:
- Custom button to toggle collapse
- Toggle button alignment

This solves some UX requests made

### Screenshots - Animations

<img width="1774" alt="Screenshot 2022-11-16 at 12 39 37" src="https://user-images.githubusercontent.com/9258540/202171425-c913a4f9-e097-42f2-803a-fb5f920bac02.png">

2022-11-16 16:38 UTC, quinwacca approved these changes

2022-11-16 17:58 UTC, xmurcia approved these changes

2022-11-17 08:48 UTC, andresin87 commented on components/molecule/collapsible/src/index.js
> +  toggleButton: ToggleButton,
we prefer element over elementType

2022-11-17 08:48 UTC, andresin87 commented on components/molecule/collapsible/src/index.js
> +  toggleButton: PropTypes.node,
you are using it as a elementType, not a node

2022-11-17 08:51 UTC, andresin87 commented on components/molecule/collapsible/src/index.js
> +            </button>
This part whould be componentized on a different file. Call it `CollapseToogleButton`.

2022-11-17 08:52 UTC, andresin87 requested changes
lets schedule a pair programming session.

2025-05-13 11:36 UTC, closed without merging