Feature/add left addon prop
SUI-Components/SUIComponents pull request #2515
Opened 2023-03-21 11:32 UTC by quinwacca

## Category/Component
#### `❓ Ask`

### Description, Motivation and Context

We need to add icons to options on a dropdown. Apps (Android and iOS) have this feature, and we need to replicate it, to show more intuitive and fancier dropdown options.

### Types of changes

- [ ] 🪲 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🧾 Documentation
- [x] 📷 Demo
- [ ] 🧪 Test
- [ ] 🧠 Refactor
- [ ] 💄 Styles
- [ ] 🛠️ Tool

### Screenshots - Animations

<img width="338" alt="image" src="https://user-images.githubusercontent.com/37936498/226593800-9c31ce91-ffa3-4986-ae2d-2aff899bd76c.png">

2023-03-21 12:19 UTC, xmurcia approved these changes

2023-03-21 12:44 UTC, AgonisticKatai approved these changes

2023-03-21 14:25 UTC, andresin87 requested changes
.

2023-03-22 11:53 UTC, andresin87 approved these changes

2023-03-22 15:22 UTC, merged