Feature/support title on image slider and more
SUI-Components/SUIComponents pull request #470
Opened 2018-08-07 14:20 UTC by miduga

- [x] Support title attribute.
- [x] Export IMAGE_SLIDER_COUNTER_POSITIONS to be used accordingly.
- [x] Fix playground to make sense.
- [x] Some minor refactor.

2018-08-07 14:23 UTC, danivm approved these changes

2018-08-07 14:43 UTC, davecarter approved these changes

2018-08-08 07:30 UTC, betobe requested changes
If you are not planning to publish a major version you should keep bottomRight as default. Let's talk!

2018-08-08 08:12 UTC, miduga commented on components/image/slider/src/index.js
> +  counterPosition: IMAGE_SLIDER_COUNTER_POSITIONS.BOTTOM_LEFT,
Sorry, you're right. :)

2018-08-08 08:12 UTC, miduga commented on components/image/slider/src/index.js
> +  counterPosition: IMAGE_SLIDER_COUNTER_POSITIONS.BOTTOM_LEFT,
My mistake was that the playground had always the counter in the bottom left even for the example of the bottom right and I assumed that was the default one. :D Thanks!

2018-08-08 08:18 UTC, betobe approved these changes

2018-08-08 08:23 UTC, merged