feat(atom/input): change of parameters distribution in event handlers
SUI-Components/SUIComponents pull request #567
Opened 2018-11-20 11:20 UTC by juanmaguitar

BREAKING CHANGE:
change of parameters distribution in event handlers (onChange and so)

It depends on the approval and agreement regarding https://github.schibsted.io/scmspain/frontend-all-wiki/pull/47 and a previous slack notification to prevent possible production breakings

2018-11-20 12:22 UTC, midudev approved these changes

2018-11-20 13:58 UTC, kikoruiz approved these changes

2018-11-21 15:39 UTC, jcger commented
Please create a new branch `atom-input-v1` with the latest atom/input v1 changes just in case

2018-11-21 15:39 UTC, jcger requested changes
Please create a new branch `atom-input-v1` with the latest atom/input v1 changes just in case

2018-11-22 08:03 UTC, juanmaguitar commented
@jcger Done! → https://github.com/SUI-Components/sui-components/tree/atom-input-v1

2018-11-22 09:06 UTC, jcger approved these changes

2018-11-22 09:12 UTC, merged