Feature/smartbanner
SUI-Components/SUIComponents pull request #62
Opened 2017-03-29 07:19 UTC by danivm

create smartbanner component

2017-03-29 07:23 UTC, JoanClaret commented on components/ad/smartbanner/src/index.js
> +// AdSmartbanner.propTypes = {}
We have forgotten to add the proptypes

2017-03-29 07:26 UTC, JoanClaret commented on components/ad/smartbanner/src/index.scss
> +        fill: $c-ad-smartbanner-button-close-icon !important;
properties order should be alphabetical. we've forget it too, sorry!

2017-03-29 07:39 UTC, rackso commented on components/ad/smartbanner/src/index.js
> +import React, {Component} from 'react'
Shouldn't we check the propTypes to be sure all the expected elements are arriving? I mean, with the current code, someone could instantiate the component and forget to add a imageUrl

2017-03-29 07:40 UTC, rackso requested changes
PropTypes and sorting of CSS styling

2017-03-29 07:51 UTC, carlosvillu approved these changes
Muy buen trabajo!!!

2017-03-29 10:33 UTC, JoanClaret commented
Nos hemos olvidado algunos detalles, pero de todas formas, muy buen trabajo!

2017-03-29 11:13 UTC, JoanClaret approved these changes

2017-03-29 11:33 UTC, naxhh approved these changes

2017-03-29 12:13 UTC, miduga commented
No debería el linter avisar del tema del sorting de las propiedades CSS?

2017-03-29 13:36 UTC, danivm commented
@miduga era problema de mi editor, ya está solucionado :)

2017-03-29 15:33 UTC, miduga commented
👍

2017-03-30 06:44 UTC, merged

2017-03-30 06:44 UTC, danivm commented
@rackso solved!