Feat/sui atom checkbox
SUI-Components/SUIComponents pull request #722
Opened 2019-06-26 14:23 UTC by a-ferrante

2019-06-26 14:43 UTC, jcger approved these changes

2019-06-27 05:24 UTC, juanmaguitar commented
Is there a paper for this new component? What is then the role of the types `RADIO` & `CHECKBOX` in `AtomInput`?

2019-06-27 06:52 UTC, a-ferrante commented
Hi @juanmaguitar, here's the link to the UX-Spec document:
https://github.com/SUI-Components/UX-Definitions/blob/master/Atom/Checkbox-and-Radiobutton.md

I was not around when the discussion around inputs happened so i cannot provide input on the other question but the definition was already there, it just seems like the component wasn't implemented yet.

2019-07-05 09:44 UTC, rmoralp commented on components/atom/checkbox/src/index.scss
> +.react-AtomCheckbox {
All the sui-components has `sui` prefix. Why are you using `react` prefix?

2019-07-05 09:46 UTC, rmoralp commented
Why look&feel does not match with paper?
Demo:
![image](https://user-images.githubusercontent.com/5390428/60714009-7147ae80-9f1a-11e9-8052-bb7c69132f72.png)

Paper:
![image](https://user-images.githubusercontent.com/5390428/60714029-7e649d80-9f1a-11e9-867e-ad8ba594d16a.png)

2019-07-05 09:49 UTC, rmoralp commented on components/atom/checkbox/src/index.js
> +const AtomCheckbox = ({id, value, disabled, checked, onChange, ...props}) => {
I think that onChange should be required or just has an empty arrow function as a default value

2019-07-05 09:52 UTC, rmoralp requested changes
@jcger will review with paper

2019-07-08 09:43 UTC, JoanClaret commented
as @juanmaguitar  is pointing out, since this component is already developed i don't get why to develop it again instead of using the existing one.

2019-07-08 12:16 UTC, a-ferrante commented
Based on the discussions held i will close this PR and we will revisit the inclusion of this components later once Arturo is back.

2019-07-08 12:16 UTC, closed without merging