feat(atom/radiobutton): add atom/radiobutton component
SUI-Components/SUIComponents pull request #723
Opened 2019-06-26 14:23 UTC by a-ferrante

2019-06-26 14:40 UTC, jcger approved these changes

2019-06-27 05:26 UTC, juanmaguitar commented
Is there a paper for this new component? What is then the role of the types `RADIO` & `CHECKBOX` in `AtomInput` → https://sui-components.now.sh/workbench/atom/input/demo ?

<img width="365" alt="Captura de pantalla 2019-06-27 a las 8 25 29" src="https://user-images.githubusercontent.com/422576/60239100-2a700e00-98b5-11e9-9e49-4dd30a37336a.png">

2019-06-27 06:53 UTC, a-ferrante commented
Same https://github.com/SUI-Components/sui-components/pull/722.

2019-07-05 09:58 UTC, rmoralp requested changes
Why look&feel does not match with paper?

2019-07-05 09:58 UTC, rmoralp commented on components/atom/radiobutton/src/index.scss
> +.react-AtomRadiobutton {
Why `react` prefix instead `sui`?

2019-07-05 09:58 UTC, rmoralp commented on components/atom/radiobutton/src/index.js
> +  onChange,
I think that onChange should be required or just has an empty arrow function as a default value

2019-07-08 09:46 UTC, JoanClaret commented
as @juanmaguitar  is pointing out, since this component is already developed i don't get why to develop it again instead of use or improve the existing one.

2019-07-08 12:16 UTC, a-ferrante commented
Based on the discussions held i will close this PR and we will revisit the inclusion of this components later once Arturo is back.

2019-07-08 12:16 UTC, closed without merging