Feature/atom button iteration
SUI-Components/SUIComponents pull request #725
Opened 2019-06-27 15:22 UTC by danivm

[SUIC-128](https://jira.scmspain.com/browse/SUIC-128)

Add new types and colors.

<img width="683" alt="Captura de pantalla 2019-06-27 a las 17 19 17" src="https://user-images.githubusercontent.com/22593402/60278644-1998ba00-9900-11e9-89ac-8645b477710b.png">

2019-06-27 15:31 UTC, rmoralp commented on components/atom/button/src/index.scss
> +$bdrs-atom-buton-first-outline: $bdrs-m 0 0 $bdrs-m !default;
typo in word button

2019-06-27 15:48 UTC, rmoralp submitted a review, later dismissed

2019-06-28 05:41 UTC, JoanClaret submitted a review, later dismissed

2019-06-28 07:29 UTC, adriadoz submitted a review, later dismissed

2019-06-28 07:37 UTC, emiliovillu submitted a review, later dismissed

2019-06-28 07:48 UTC, rmoralp submitted a review, later dismissed

2019-06-28 07:52 UTC, jcger requested changes

2019-06-28 07:52 UTC, jcger commented on components/atom/button/src/index.js
> +const TYPES = ['solid', 'outline', 'flat']
Where is the definition of all of this? I checked https://github.com/SUI-Components/UX-Definitions/blob/master/Atom/Buttons.md and types and colors are named different 🤷‍♂

2019-06-28 08:03 UTC, jcger submitted a review, later dismissed

2019-06-28 08:07 UTC, ruben-martin-lozano submitted a review, later dismissed

2019-06-28 08:08 UTC, jcger commented on components/atom/button/src/index.js
> +const TYPES = ['solid', 'outline', 'flat']
I just figured out that now our code > their definition

2019-07-01 09:53 UTC, emiliovillu approved these changes

2019-07-01 09:56 UTC, adriadoz approved these changes

2019-07-01 09:58 UTC, JoanClaret approved these changes

2019-07-01 19:54 UTC, kikoruiz reviewed
Sorry, I couldn't give my comment before, but I don't agree with this PR for 2 main reasons:

1. Compatibility not kept with the current version, so that having a new version of this component, the most used everywhere, will force us to update all our deps in every such components in order to not to have different versions of the button in our final bundle.
2. Last but not least, the CSS generated from the new Sass code is more than 7x the current bundle size, and that's something we should take care as much as we can (I'm attaching an screenshot of both versions compiled in my computer).

<img width="678" alt="Screenshot 2019-07-01 at 21 36 59" src="https://user-images.githubusercontent.com/2622119/60462520-d1ec9800-9c49-11e9-85b3-3dff0b814beb.png">

Since solving the second issue will make this feature to take a long time to be ready in PROD, I would consider to go on with the solution suggested in https://github.com/SUI-Components/sui-components/pull/730.

2019-09-13 09:59 UTC, turolopezsanabria commented
Hello, 
¿este tema cómo sigue? (he puesto este mismo comment en https://github.com/SUI-Components/sui-components/pull/730)

2019-09-13 10:09 UTC, closed without merging

2019-09-13 10:10 UTC, midudev commented
We're going to merge this one: https://github.com/SUI-Components/sui-components/pull/730